- name: Ensure SELinux is set to disabled mode
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled

- name: Set MAPR_SUBNETS Environment Variable
  replace:
    path: /opt/mapr/conf/env.sh
    regexp: '^#?export MAPR_SUBNETS=.*$'
    replace: 'export MAPR_SUBNETS=10.248.0.0/16'

- name: Set net.ipv4.tcp_retries2
  sysctl:
    name: net.ipv4.tcp_retries2
    value: 5
    state: present

- name: Set vm.swappiness
  sysctl:
    name: vm.swappiness
    value: 1
    state: present

- name: Set net.core.rmem_max
  sysctl:
    name: net.core.rmem_max
    value: 16777216

- name: Set net.core.rmem_default
  sysctl:
    name: net.core.rmem_default
    value: 16777216

- name: Set net.core.wmem_max
  sysctl:
    name: net.core.wmem_max
    value: 16777216

- name: Set net.core.wmem_default
  sysctl:
    name: net.core.wmem_default
    value: 16777216

- name: Set net.ipv4.tcp_rmem
  sysctl:
    name: net.ipv4.tcp_rmem
    value: 4096 87380 16777216

- name: Set net.ipv4.tcp_wmem
  sysctl:
    name: net.ipv4.tcp_wmem
    value: 4096 87380 16777216

- name: Set net.ipv4.tcp_mem
  sysctl:
    name: net.ipv4.tcp_mem
    value: 4096 87380 16777216

- name: Disable transparent huge pages for performance
  shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag
